### ISSUE TITLE
Debugger a scrolování kolečkem myši

### ISSUE THREAD

**Issue by 72ka** [omikron88/jondra#1]
Ahoj JOndru používám k veškerému vývoji pro Ondru a už si to ani bez něj neumím představit a moc děkuji za to že je a v poslední verzi je opravdu i naprosto reálně rychlý. Je tam však nějaká chybka a dělá mi to na dvou PC a to, že když v debuggeru roluju kolečkem myši po adresách s výpisem obsahu paměti nahoru a dolů, tak se špatně přepisují řádky s obsahem paměti. Napraví to až opět ruční zadání adresy nebo vypnutí a zapnutí debuggeru.

**Comment by tmilata** [comment]
Ahoj.
Jedná se o HEX výpis paměti po bytech, nebo o výpis instrukcí assembleru?
Projevuje se ta chyba hned od začátku, nebo až po nějakém čase užívání?

**Comment by tmilata** [comment]
Jednalo se o výpis assembleru při rolování zpět. Rolovalo se to po 1 bajtu, nyní bylo změněno tak, že se predikuje, jak dlouhá instrukce předchází tu, co je zobrazena jako první a o tolik bajtů se posune zpět.
