### ISSUE TITLE
Implementace OndraMELODIK

### ISSUE THREAD

**Issue by 72ka** [omikron88/jondra#2]
Ahoj, bylo by možné prosím výhledově dodělat emulaci [OndraMELODIK](https://github.com/72ka/OndraMELODIK) (čipu SN76489)?. Používám jondru při vývoji a hrozně by mi to pomohlo, alespoň na hrubé odladění programu zvuků a hudby. Díky

**Comment by tmilata** [comment]
Doplněno.
